[package]
name = "tuntap"
version = "0.2.0"
authors = [
    "Vanhala Antti <antti.vanhala@aalto.fi>",
    "Matthew Bentley <matthew@bentley.link>",
    "Misuzu <bakalolka@gmail.com>",
]
license = "MIT"
build = "build.rs"

[dependencies]
libc = "^0.2"
